development:
  adapter: postgresql
  encoding: unicode
  database: tweet_dev
  pool: 5
  host: localhost
  username: lisafeatherknee

test:
  adapter: postgresql
  encoding: unicode
  database: tweet_test
  pool: 5
  host: localhost
  username: lisafeatherknee

production:
  adapter: postgresql
  encoding: unicode
  database: tweet_production
  pool: 5
  username: lisafeatherknee